name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # or your main branch name, e.g., main or master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy

    permissions:
      contents: write # Required to deploy to GitHub Pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Use v4 for latest node versions
        with:
          node-version: '20.x' # Or your preferred Node.js version

      - name: Install dependencies
        run: npm install # or pnpm install or yarn install if you use those

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Your build output folder, usually 'dist' for Vite
          force_orphan: true # Optional: force orphan to clean up gh-pages branch for each deploy if needed
